CREATE TABLE `api_keys` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`authority_id` bigint unsigned,
	`key_name` varchar(255) NOT NULL,
	`key_value` varchar(500) NOT NULL,
	`key_prefix` varchar(20) NOT NULL,
	`permissions` json,
	`rate_limit` int DEFAULT 1000,
	`is_active` boolean NOT NULL DEFAULT true,
	`expires_at` timestamp,
	`last_used_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `api_keys_id` PRIMARY KEY(`id`),
	CONSTRAINT `api_keys_key_value_unique` UNIQUE(`key_value`)
);
--> statement-breakpoint
CREATE TABLE `audit_logs` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`user_id` bigint unsigned NOT NULL,
	`user_name` varchar(255),
	`user_role` varchar(50),
	`action` varchar(255) NOT NULL,
	`action_category` enum('authentication','authority_management','user_management','enrollment','document','verification','biometric','card_issuance','payment','system','api_access') NOT NULL,
	`entity_type` varchar(100),
	`entity_id` varchar(255),
	`entity_ref` varchar(255),
	`details` text,
	`metadata` json,
	`ip_address` varchar(50),
	`user_agent` text,
	`previous_value` json,
	`new_value` json,
	`severity` enum('info','warning','error','critical') NOT NULL DEFAULT 'info',
	`success` boolean NOT NULL DEFAULT true,
	`error_message` text,
	`previous_log_hash` varchar(128),
	`log_hash` varchar(128),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `authorities` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`unique_authority_id` varchar(50) NOT NULL,
	`authority_name` varchar(255) NOT NULL,
	`authority_code` varchar(50) NOT NULL,
	`registration_number` varchar(100),
	`address` text,
	`contact_number` varchar(50),
	`email` varchar(320),
	`digital_signature` text,
	`signature_image_url` text,
	`signing_certificate` text,
	`is_active` boolean NOT NULL DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `authorities_id` PRIMARY KEY(`id`),
	CONSTRAINT `authorities_unique_authority_id_unique` UNIQUE(`unique_authority_id`),
	CONSTRAINT `authorities_authority_code_unique` UNIQUE(`authority_code`)
);
--> statement-breakpoint
CREATE TABLE `biometrics` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`application_id` bigint unsigned NOT NULL,
	`fingerprints` json,
	`left_iris` text,
	`right_iris` text,
	`face_photo_url` text,
	`face_photo_data` longtext,
	`liveness_check` boolean NOT NULL DEFAULT false,
	`liveness_score` decimal(5,2),
	`device_id` varchar(100),
	`device_name` varchar(255),
	`device_certified` boolean NOT NULL DEFAULT false,
	`capture_quality` enum('low','medium','high','excellent') DEFAULT 'medium',
	`is_encrypted` boolean NOT NULL DEFAULT true,
	`encryption_key` varchar(255),
	`checksum` varchar(128),
	`captured_by` bigint unsigned,
	`captured_at` timestamp NOT NULL DEFAULT (now()),
	`verified_at` timestamp,
	`deduplication_check` boolean NOT NULL DEFAULT false,
	`deduplication_result` enum('pass','fail','pending') DEFAULT 'pending',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `biometrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `card_print_queue` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`card_id` bigint unsigned NOT NULL,
	`application_id` bigint unsigned NOT NULL,
	`printer_id` bigint unsigned,
	`priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
	`status` enum('queued','printing','printed','failed','cancelled') NOT NULL DEFAULT 'queued',
	`print_attempts` int NOT NULL DEFAULT 0,
	`error_message` text,
	`printed_by` bigint unsigned,
	`printed_at` timestamp,
	`queued_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `card_print_queue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `devices` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`authority_id` bigint unsigned NOT NULL,
	`device_id` varchar(100) NOT NULL,
	`device_name` varchar(255) NOT NULL,
	`device_type` enum('fingerprint_scanner','iris_scanner','camera','card_printer','smart_card_encoder') NOT NULL,
	`manufacturer` varchar(255),
	`model` varchar(255),
	`serial_number` varchar(100),
	`certification_number` varchar(100),
	`certification_expiry` timestamp,
	`is_certified` boolean NOT NULL DEFAULT false,
	`is_active` boolean NOT NULL DEFAULT true,
	`last_connected_at` timestamp,
	`firmware_version` varchar(50),
	`ip_address` varchar(50),
	`registered_by` bigint unsigned,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `devices_id` PRIMARY KEY(`id`),
	CONSTRAINT `devices_device_id_unique` UNIQUE(`device_id`)
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`application_id` bigint unsigned NOT NULL,
	`file_url` text NOT NULL,
	`file_name` varchar(255) NOT NULL,
	`document_type` enum('driver_license','voter_id','passport','address_proof','utility_bill','photo','other') NOT NULL,
	`file_size` int,
	`mime_type` varchar(100),
	`version` int NOT NULL DEFAULT 1,
	`is_encrypted` boolean NOT NULL DEFAULT false,
	`checksum` varchar(128),
	`uploaded_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `identity_applications` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`application_ref` varchar(50),
	`identity_number` varchar(50),
	`first_name` varchar(255) NOT NULL,
	`middle_name` varchar(255),
	`last_name` varchar(255) NOT NULL,
	`date_of_birth` varchar(50) NOT NULL,
	`gender` enum('Male','Female','Other') NOT NULL,
	`blood_group` varchar(10),
	`nationality` varchar(100) NOT NULL,
	`marital_status` enum('Single','Married','Divorced','Widowed'),
	`education_level` varchar(255),
	`profession` varchar(255),
	`professional_address` text,
	`mobile_number` varchar(50) NOT NULL,
	`email` varchar(320),
	`address` text NOT NULL,
	`photo_url` text,
	`status` enum('draft','submitted','under_review','correction_requested','biometric_pending','biometric_captured','verification_pending','approved','payment_pending','payment_completed','card_generation_pending','card_printed','issued','active','suspended','revoked','expired','rejected') NOT NULL DEFAULT 'draft',
	`authority_id` bigint unsigned NOT NULL,
	`created_by` bigint unsigned NOT NULL,
	`verified_by` bigint unsigned,
	`remarks` text,
	`payment_amount` decimal(10,2),
	`payment_status` enum('pending','completed','failed','refunded') DEFAULT 'pending',
	`biometric_status` enum('pending','captured','verified','failed') DEFAULT 'pending',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `identity_applications_id` PRIMARY KEY(`id`),
	CONSTRAINT `identity_applications_application_ref_unique` UNIQUE(`application_ref`),
	CONSTRAINT `identity_applications_identity_number_unique` UNIQUE(`identity_number`)
);
--> statement-breakpoint
CREATE TABLE `identity_cards` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`application_id` bigint unsigned NOT NULL,
	`identity_number` varchar(50) NOT NULL,
	`card_serial_number` varchar(100),
	`qr_code_url` text NOT NULL,
	`qr_code_data` text,
	`pdf_url` text,
	`card_data` json,
	`chip_data` json,
	`nfc_data` json,
	`public_key_certificate` text,
	`verification_token` varchar(255),
	`digital_signature` text,
	`hologram_code` varchar(50),
	`barcode_data` varchar(255),
	`print_status` enum('pending','printed','failed','reprinted') DEFAULT 'pending',
	`print_date` timestamp,
	`chip_encoded` boolean NOT NULL DEFAULT false,
	`chip_encoded_at` timestamp,
	`issued_at` timestamp NOT NULL DEFAULT (now()),
	`expires_at` timestamp,
	`is_active` boolean NOT NULL DEFAULT true,
	`revoked_at` timestamp,
	`revoke_reason` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `identity_cards_id` PRIMARY KEY(`id`),
	CONSTRAINT `identity_cards_identity_number_unique` UNIQUE(`identity_number`),
	CONSTRAINT `identity_cards_card_serial_number_unique` UNIQUE(`card_serial_number`)
);
--> statement-breakpoint
CREATE TABLE `password_reset_tokens` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`user_id` bigint unsigned NOT NULL,
	`token` varchar(255) NOT NULL,
	`expires_at` timestamp NOT NULL,
	`used` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `password_reset_tokens_id` PRIMARY KEY(`id`),
	CONSTRAINT `password_reset_tokens_token_unique` UNIQUE(`token`)
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`application_id` bigint unsigned NOT NULL,
	`invoice_number` varchar(100),
	`amount` decimal(10,2) NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'USD',
	`status` enum('pending','processing','completed','failed','refunded','cancelled') NOT NULL DEFAULT 'pending',
	`payment_method` enum('cash','card','upi','bank_transfer','online','government_voucher') DEFAULT 'cash',
	`transaction_id` varchar(255),
	`gateway_reference` varchar(255),
	`gateway_response` json,
	`receipt_url` text,
	`invoice_pdf_url` text,
	`paid_by` bigint unsigned,
	`paid_at` timestamp,
	`refunded_at` timestamp,
	`refund_reason` text,
	`failure_reason` text,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payments_id` PRIMARY KEY(`id`),
	CONSTRAINT `payments_invoice_number_unique` UNIQUE(`invoice_number`)
);
--> statement-breakpoint
CREATE TABLE `platform_users` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`password` varchar(255) NOT NULL,
	`platform_role` enum('operator','verification_officer','authority_admin','super_admin','card_printing_operator') NOT NULL DEFAULT 'operator',
	`authority_id` bigint unsigned,
	`is_active` boolean NOT NULL DEFAULT true,
	`mfa_enabled` boolean NOT NULL DEFAULT false,
	`mfa_secret` varchar(255),
	`last_password_change` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `platform_users_id` PRIMARY KEY(`id`),
	CONSTRAINT `platform_users_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
CREATE TABLE `sessions` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`user_id` bigint unsigned NOT NULL,
	`token` varchar(500) NOT NULL,
	`ip_address` varchar(50),
	`user_agent` text,
	`device_info` json,
	`is_active` boolean NOT NULL DEFAULT true,
	`expires_at` timestamp NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`last_activity` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `sessions_token_unique` UNIQUE(`token`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`unionId` varchar(255) NOT NULL,
	`name` varchar(255),
	`email` varchar(320),
	`avatar` text,
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	`lastSignInAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_unionId_unique` UNIQUE(`unionId`)
);
